---
title: "Formation et parcours de recherche "
author: "Anouk MARTIN"
output: pdf_document
fontsize: 12pt
geometry: margin=0.7in
header-includes:
- \usepackage{booktabs}
- \usepackage{mathptmx}
- \usepackage[T1]{fontenc}
- \usepackage{multirow}
- \usepackage[table,xcdraw]{xcolor}
- \usepackage{indentfirst}
- \usepackage{pdfpages}
- \usepackage{pdfpages}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \renewcommand{\headrulewidth}{0.7pt}
- \fancyhead[C]{} 
- \fancyhead[R]{Anouk MARTIN}
- \fancyhead[L]{Formation et parcours de recherche}
---

\setlength{\parindent}{1.2cm}

\newpage

Après une CPGE lettres et sciences sociales (BL) et une année dans le parcours sciences sociales et politiques du CPES de PSL, j'ai intégré le département de sciences sociales de l'ENS par le biais du concours étudiant en 2019. L'année blanche effectuée en première année m'a permis de me consacrer à la lecture approfondie d'ouvrages de sociologie, de suivre des enseignements d'autre disciplines (notamment en géographie, histoire, économie et informatique) et de participer à la vie de l’École via des séminaires d'élèves comme le séminaire *Lecture de Marx* ou des ateliers transdisciplinaires comme le stage de géographie ou celui de photographies et sciences sociales. Cette pluridisciplinarité qui caractérise mon parcours universitaire depuis la première année se retrouve dans mon projet de thèse qui prend pour objet d'étude sociologique des pratiques économiques, et dans l'école doctorale Pratiques et théorie du sens que je souhaite intégrer l'année prochaine.

J’ai été formée à la recherche en sciences sociales sur le campus Jourdan, au sein du master QESS où j'ai pu y apprendre les méthodes quantitatives pour les sciences sociales. Grace aux enseignement suivis dans ce cadre, je maîtrise désormais une pluralité de techniques statistiques que j'ai pu mettre en oeuvre d'abord dans mon mémoire de M1 qui cherchait à fournir une explication sociologique aux non-réponses à un questionnaire. Les six mois passés à la DREES, service statistique du ministère de la santé et des solidarités, comme chargée d'étude sur les retraites m'ont permis d’acquérir un très grande autonomie dans le traitement de données sous le logiciel *R* puisque j'ai participé à l'écriture de l'ouvrage *Les retraités et les retraites* (2023). Cette expérience m'a aussi permis de développer une fine connaissance du fonctionnement de la statistique publique et des sources de données existantes qui sera, j'en suis sûre, utile en doctorat. Enfin, en écho avec les enseignements en sociologie et histoire de la quantification suivis dans le cadre du master, ce poste de travail m'a permis d’observer la production statistique routinière et convaincu d'adopter une approche réflexive des conventions statistiques et des données produites. C'est cette approche quantitative à la fois exigente sur le plan statistique et critique que je m'efforce de mettre en oeuvre cette année dans mon mémoire portant sur les arrangements économiques dans les familles recomposées en interrogeant la pertinence du "ménage" au prisme de l'économie domestique, et que je continuerais à développer en doctorat.

Le cadre d'étude offert par département de sciences sociales m'a aussi permis de compléter ce cursus quantitatif par une formation aux méthodes qualitatives. Chaque année, j'ai au à cœur de choisir des ateliers de recherche ethnographiques qui m'ont offert de véritables expériences de recherche collectives et permis d'être à l'aise dans la pratique de l'enquête de terrain. J'ai aussi participé à une enquête collective associant des chercheurs et doctorants de l'IRISSO à des lycéens de Saint-Denis au cours du confinement du printemps 2020. Durant cette période, j'ai réalisé un suivi longitudial de deux couples ayant des enfants, à raison de deux entretiens par semaine avec chacun des conjoints. Très formatrice sur le plan méthologique, cette enquête a aussi nourri mes interets de recherche en sociologie de la famille. Elle a ainsi donné lieu à la publication de deux articles co-écrits dans des revues à comité de lecture. Un premier, publié en 2021 dans la *Revue des politiques sociales et familiales* porte sur le genre de l'appropriation de l'espace domestique pendant le confinement, et a été présenté et discuté au séminaire de l’unité Logement et inégalités spatiales de l’INED en 2022. Un second article, synthèse des nombreuses discussions ayant animé le collectif, publié dans *Genèses* en 2023, traite de enjeux méthodologiques propres aux enquêtes portant sur des proches et interroge l'usage de la catégorie d'intime en sociologie.

blablab écriture et valorsation scientificques, exigences des comités de lecture etc. blablbla crespa super

Nourrit par de nombreuses expériences comme tutrice, professeure particuliere ou encore animatrice, j'ai developpé un gout pour l'enseignement, que je considère faire partie intégrante de ????. C'est dans cet esprit que j'ai choisit de préparer l’agrégation de sciences économique et sociale en 2022, à laquelle j'ai été reçue quatrième. Au delà de solides connaissances générales en sociologie et en économie, ce fut aussi l’occasion d'apprendre à préparer rapidement des exposés synthétiques et clairs en choisissant une bibliographie pertinente. Cela sera, j'en suis sûre, d'une grande aide lors de la préparation de cours. L'université Paris 8 Vincennes Saint Denis, à laquelle est étroitement liée le CRESPPA, possède une licence de sciences sociales dans laquelle les enseignement dispensé sont de qualité, dont certains étudiants faisaient partie des lycéens impliqués dans l’enquête collective sur le confinement. J'aurais sans nul doute un grand plaisir à y enseigner.

# Enseignement

Le département de sciences sociales m'a offert la possibilité au sein du master de sciences sociales dans le parcours QESS. J’ai pu y apprendre à la fois les méthodes qualitatives et quantitatives, dans un ancrage interdisciplinaire important. D’une part, j’ai produit deux enquêtes ethnographiques, toutes deux sur des terrains médicaux. À l’occasion de mon mémoire de M1, j’ai réalisé un terrain de six mois dans une maison d’arrêt, afin d’étudier la prise en charge de la santé sexuelle des femmes détenues. Lors de mon mémoire de M2, j’ai assisté à des consultations de dermatologie professionnelle dans un service hospitalier de médecine du travail. D’autre part, j’ai appris à manier l’analyse statistique sur des enquêtes quantitatives d’envergure nationale. J’ai notamment participé à un atelier de recherche autour des répercussions socioéconomiques de la crise sanitaire sur les travailleurs et travailleuses de l’hôtellerie-restauration, en mobilisant des statistiques descriptives, des régressions, des analyses factorielles et des études longitudinales de trajectoires.

\#######################

Après une licence au Cycle Pluridisciplinaire d’Études Supérieures (CPES) de PSL, j’ai intégré l’ENS par le biais du concours étudiant en 2019. J’ai commencé par y passer une année blanche, durant laquelle j’ai pu assister à de nombreux cours – en particulier de sociologie et d’histoire – mais aussi m’investir dans deux séminaires d’élèves qui m’ont accompagnée durant toute ma scolarité. Grâce au séminaire Lectures de Marx, dont j’ai rapidement rejoint l’équipe d’organisation, j’ai pu chaque année animer des séances devant un public avisé. Grâce au séminaire Actualité critique, que j’ai d’abord suivi en tant qu’élève à mon arrivée à l’ENS, puis que j’ai encadré comme assistante pédagogique aux côtés de Blaise Wilfert (DSS) et désormais de Christian Lorenzi (DEC), j’ai accompagné pendant 3 ans des groupes d’étudiant·e·s dans la préparation de conférences.

J’ai été formée à la recherche en sciences sociales sur le campus Jourdan au sein du master PDI. J’ai pu y apprendre à la fois les méthodes qualitatives et quantitatives, dans un ancrage interdisciplinaire important. D’une part, j’ai produit deux enquêtes ethnographiques, toutes deux sur des terrains médicaux. À l’occasion de mon mémoire de M1, j’ai réalisé un terrain de six mois dans une maison d’arrêt, afin d’étudier la prise en charge de la santé sexuelle des femmes détenues. Lors de mon mémoire de M2, j’ai assisté à des consultations de dermatologie professionnelle dans un service hospitalier de médecine du travail. D’autre part, j’ai appris à manier l’analyse statistique sur des enquêtes quantitatives d’envergure nationale. J’ai notamment participé à un atelier de recherche autour des répercussions socioéconomiques de la crise sanitaire sur les travailleurs et travailleuses de l’hôtellerie-restauration, en mobilisant des statistiques descriptives, des régressions, des analyses factorielles et des études longitudinales de trajectoires.

Par ailleurs, j’ai bénéficié de nombreuses expériences de recherches collectives. J’ai ainsi occupé le poste d’assistante de recherche pendant 3 ans au sein du projet ANR Global Youth portant sur l’histoire des circulations étudiantes internationales. Au sein d’une équipe d’historien·ne·s et de sociologues, j’ai réalisé un travail d’archives, de saisie de données et de traitement statistique des dossiers d’admission à la Cité Universitaire de Paris entre 1929 et 1964. J’ai également éprouvé l’écriture collective d’un article, de ses prémisses à sa soumission à une revue, à l’occasion d’un cours du master PDI portant sur l’analyse des révolutions en sciences sociales. Les enquêtes que j’ai menées m’ont conduite à fréquenter les espaces scientifiques pour y exposer mes travaux. J’ai ainsi participé à trois colloques en 2021 et 2022 : le congrès de l’Association des Professionnels de Santé exerçant en prison (APSEP), la journée d’études « Enfanter : pratiques et discours » se tenant à l’université Lyon 1, et le colloque « Santé et sexualité » organisé à l’Institut national des Études Démographiques (INED). J’ai également écrit un article pour la revue Champ Pénal à partir de mon mémoire de M1, à paraître au printemps 2023 dans un dossier intitulé « Genre et carrières délinquantes ». Cette familiarisation aux lieux de valorisation scientifique est allée de pair avec des premières expériences d’enseignement, d’abord par le biais du séminaire Actualité critique puis par deux interventions sur le thème « Genre et pauvreté » au sein de l’Institut d’Enseignement Supérieur de Travail social (IESTS) de Nice pour des classes d’assistantes sociales en formation.

Ma demande d’allocation pour un Contrat doctoral spécifique normalien (CDSN) s’inscrit dans la continuité de ces expériences de recherche et d’enseignement. L’inscription en thèse sur le sujet de l’usure des mains au travail me permettra de poursuivre le chantier entrepris en M2, auprès de directeurs spécialisés sur ces questions. L’expertise de Romuald Bodin en sociologie du handicap sera une ressource précieuse pour accompagner l’axe de ma thèse portant sur le maintien en activité des travailleurs et travailleuses usé·e·s. Je continuerai par ailleurs d’être encadrée par Anton Perdoncin, avec qui la collaboration est rendue aisée par nos intérêts scientifiques convergents et notre connaissance de longue date. Je bénéficierai enfin dans mon laboratoire d’un environnement favorable au développement de mes recherches, grâce aux sous-axes « Santé et risques professionnels » et « Emploi, travail et recomposition du salariat d'exécution » dont dispose le Centre nantais de sociologie (Cens).
