---
title: "L'optimisation fiscale ordinaire. Le genre des arrangements familiaux avec le système socio-fiscal."
subtitle: "Projet de thèse"
author: "Anouk MARTIN"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output:
  pagedown::html_paged:
    toc: false
    number_sections: false
    css: 
      notes.css
    self_contained: false
lot: false # insert a list of tables
lof: false # insert a list of figures
paged-footnotes: true
# uncomment this line to produce HTML and PDF in RStudio:
# knit: pagedown::chrome_print
editor_options: 
  chunk_output_type: console
bibliography: biblio_projet_these.bib
csl: revue-francaise-de-sociologie.csl
---

# Introduction

Presque absente du débat politique au milieu des années 1980, la thématique de la fraude aux prestations sociales occupe désormais une place centrale dans le débat public portant sur la sécurité sociale et plus généralement sur le financement de l'État [@dubois2020]. Pourtant, les montants concernés parce cette "pauvre fraude" restent sans commune mesure avec la fraude fiscale qui pèse largement plus dans le budget de l'État [@dubois2021, p.423]. Ainsi, d'un côté, les travaux de sociologie portant sur la fraude fiscale ont envisagé celle-ci comme un illégalisme idéal-typique de la bourgeoisie [@sutherland1983; @lascoumes1997] et ont montré que les pratiques d'optimisation et de fraude fiscale sont situées dans les classes sociales les plus riches et concernent des montants plus importants [@spire2012]. De l'autre coté, les travaux portant sur la fraude aux prestations sociales s'intéressent d'avantage aux classes populaires et insistent sur les erreurs de déclaration commises face à un ensemble de règles complexes, les erreurs provenant des administrations elles-mêmes et sur l'intensité des contrôles subis par les bénéficiaires dont les marges de manœuvres sont réduites [@dubois2021].

Nous voudrions ici prendre pour objet d'étude l'ensemble de ces pratiques de fraude, d'optimisation ou d'erreur commises par les administrés, qu'elles concernent la fiscalité ou les prestations sociales. Ceci suppose d'effectuer plusieurs mouvements. D'abord, il s'agira de penser la fraude et l'optimisation sur un *"continuum entre l'optimisation tolérée par les textes et celle qui s'exerce en violant les règles"* [@spire2011, p.5] et d'évacuer la distinction, rarement pertinente, entre fraude et erreur [@dubois2009]. Refuser ces oppositions permet de penser ensemble une diversité de pratiques en matière de formalisation administrative, de déclaration aux institutions et de répartition économique des dépenses fiscales et prestations sociales, que l'on propose de considérer comme des "arrangements familiaux" [@bessière2022] puisque les dispositifs fiscaux et les aides sociales sont largement conjugalisés et familialisés en France [@lenoir2003]. Il ne s'agit donc plus déterminer quelle pratique relève de l'optimisation, de la fraude, de l'erreur, mais de penser la qualification sociale et judiciaire de ces pratiques comme des processus différenciés et traversés par des rapports sociaux de classe, de sexe et de race.

Ce premier mouvement invite à un second : considérer que ces arrangements avec les règles de l'État social ne concernent ni seulement les plus riches, ni seulement les plus pauvres, mais relèvent de pratiques ordinaires, dont l'exemple le plus trivial est sans doute celui des couples se mariant "pour les impôts". Si les classes populaires entretiennent un rapport plus distant aux règles de calculs de l'État social que les classes dominantes [@spire2018], elles ne subissent pas passivement leur application pour autant [@dubois2015] et sont, en particulier les femmes y appartenant, largement socialisées à prendre en charge le travail administratif qu'engendre la perception d'aides sociales [@siblot2006]. Cela ne signifie pas pour autant évacuer la question de la différenciation sociale de ces pratiques. Les classes populaires, en particulier les fractions les moins stables, sont d'avantages concernées par les prestations sociales que les classes aisées, qui sont elles-même d'avantage concernés par les impôts directs que les classes populaires : ***[mettre des chiffres RSA vs foyers imposables par exemple]***. Pour autant, tous les foyers, mêmes non-imposables, sont concernés par la déclaration d'impôt et les allocations familiales sont distribuées sans conditions de ressources, ce qui autorise à étudier ces pratiques dans tous les groupes sociaux.

On le voit, ce deuxième mouvement invite à un troisième : ces arrangements familiaux se déployant dans divers groupes sociaux, ils ne peuvent alors être étudiés qu'a condition de considérer ensemble les avantages fiscaux et les prestations sociales. À l'échelle individuelle, le fisc et la CAF font en effet partie de la catégorie pratique des "administrations" auxquelles les individus sont régulièrement confrontés [@siblot2005]. A l'échelle agrégée, les travaux récents ont bien montré la pertinence d'étudier les effets de l'ensemble du système socio-fiscal français pour analyser la répartition secondaire des revenus [@piketty2013]. En outre, si l'impôt a toujours été considéré comme un objet central en sociologie de l'État [@elias1975], les prestations sociales déterminent également le régime d'articulation entre Etat, marché et famille [@esping-andersen2007]. De ce fait, le système socio-fiscal constitue un des points d'interface entre les deux institutions que sont l'État et la famille. Plus encore, la fiscalité et les prestations sociales sont deux éléments clés permettant de comprendre la manière dont l'État façonne les rapports sociaux de sexe [@lewis1992 ; @orloff1996]. **Ainsi au croisement de la sociologie du rapport à l'État, de la sociologie économique de la famille et de la sociologie du genre, ce travail de recherche, en prenant pour objet les arrangements familiaux avec le système socio-fiscal, a pour objectif de contribuer à une réflexion sur la manière dont l'État façonne, les rapports sociaux de genre en encadrant les relations conjugales et familiales, et ce de manière différenciée selon les autres rapports sociaux**.

Nous proposons d'étudier ces arrangements en devloppant trois axes de reflexions. Ces arrangements économiques avec le système socio-fiscal peut être analysés sur deux plans : celui de la déclaration de situation et de la demande de prestation (*ex-ante*) et celui de la répartition des dépenses ou remboursements fiscaux et des prestations sociales (*ex-post*)

# Perspectives de recherche

## [Axe 1]{.underline}. Fraude, erreur ou optimisation : étudier les marges de manœuvres permises par la familialisation du système socio-fiscal

Il est vrai que le système socio-fiscal français ni simple ni toujours très cohérent : suivant que les couples sont unis légalement (mariage, pacs) ou non, qu'ils cohabitent ou non, ils n'obtiennent pas les mêmes avantages fiscaux et prestations sociales. Les conjoints séparés, divorcés ou simplement non-unis légalement peuvent choisir lequel des deux déclare les parts fiscales que représentent les enfants communs. Les parents séparés bénéficient d'une demi-part fiscale supplémentaire, mais s'ils se remettent en couple et cohabitent, cette demi-part disparaît. Rien n'encadre précisément la répartition entre conjoints des prestations sociales, versées par défaut au conjoint possédant le compte CAF pour la famille. Enfin, la répartition de la charge fiscale de l'impôt sur le revenu est, depuis la mise en place du prélèvement à la source en 2019, par défaut proportionnelle aux revenus des conjoints, mais la modification des taux de prélèvement reste entièrement possible.

Ces formes de décalages entre les règles de calcul des différentes administrations de l'État social ont souvent été analysées comme les effets d'un retard du droit civil de la famille par rapport aux évolutions sociales : augmentation de la part des couples en union libre (**? trouver une ref)**, banalisation des divorces et séparations [@chatain2020 ; @théry1993], apparition de nouvelles formes familiales [@théry1987] ou encore individualisation des patrimoines [@frémeaux2019]. Dans la sphère administrative, on analyse plutôt ces décalages comme des incohérences qui rendent le système socio-fiscal peut lisible pour les administrés [@coursdescomptes2023] . Tributaires d'une vision dukheimienne du droit comme cristallisation des transformations sociales [@durkheim1893], ces analyses occultent la force productrice du droit [@bourdieu1986]. Ainsi considérer que la CNAF qui reconnait la cohabitation entre conjoints n'est pas en cohérence avec le fisc qui ne reconnait que l'union légale (mariage ou pacs) pour conjugaliser droits sociaux ou avantages fiscaux, c'est oublier que cette conjugalisation de l'impôt fut un des arguments mobilisés par les associations de défense de droits des gays et lesbiennes pour la création du PACS et qu'elle reste un des motifs pour lequel les individus ont recours à une union légale [@rault2007]. L'État moderne libéral a construit une séparation stricte entre la sphère publique, espace dans lequel s'exerce la souveraineté de l'État, et la sphère privée, qui doit être protégée contre toute intrusion de l'État [@bereni2008]. Ainsi les réticences de l'État social à régler la totalité de ce qui se passe à l'intérieur des familles ne sont pas si étonnantes, elles caractérisent ce que Rémi @lenoir2003 a appelé un *familialisme d'État* par lequel l'État fait de la famille à la fois le support élémentaire des politiques sociales et une unité insécable relevant du privé dans laquelle l'État n'a pas à s'immiscer.

Dès lors, ces décalages dans les règles de calculs des avantages fiscaux et prestations sociales sont moins intéressants à analyser comme des incohérences ou des inadaptations que comme les résultats d'un système socio-fiscal largement conjugalisé et familialisé, qui constituent autant d'espaces de marges de manœuvre pour les individus. On préférera donc parler d'*arrangements familiaux* [@bessière2022] avec le système socio-fiscal. En plus d'évacuer la connotation morale, ce terme permet d'éviter l'économicisme consistant à supposer que les pratiques étudiées sont des choix qui répondent à des calculs rationnels d'optimisation à l'échelle de la famille [@becker1998] qui viseraient avant tout à réduire le montant d'impôt payé (les *outputs*) et maximiser le montant de prestations sociales perçues (les *inputs*) comme peuvent le faire les travaux d'économie portant sur les incitations des allocations familiales à la fécondité [@gauthier1997] ou sur les incitations fiscales au travail des femmes [@carbonnier2021]. Cela ne signifie pas pour autant ignorer la logique de ces arrangements : Céline Bessière et Sibylle Gollac [-@bessière2020] ont bien montré que la réduction du montant de l'impôt sur les successions est un des moteurs des arrangements économiques familiaux au moment de l'héritage. Si pratiques d'optimisation il y a, il faut alors se demander pour qui l'arrangement est optimisé. En fonctions de l'inégalité des revenus dans le couples, du partage des dépenses ou encore de la part des ressources mises en commun, les conjoints n'ont pas nécessairement les mêmes intérêts à ces arrangements. Plus que le terme de négociation, qui fait du résultats de celle-ci le fruit de capacités individuelles à imposer ses intérêts, le terme d'*arrangement* permet de "*penser la production plus ou moins formalisée d'un consensus entre des personnes apparentées qui ont éventuellement des intérêts contradictoires et sont prises localement dans des rapports de pouvoir, et plus généralement dans des rapports de domination qui les dépassent*" [@bessière2022, p. 49]. Ces précisément la place que prennent ces rapports de pouvoir et de domination dans la production de ces arrangement que l'on étudiera.

## [Axe 2.]{.underline} Déclaration aux institutions et formalisation des relations familiales : des catégories familiales administratives aux catégories ordinaires

Dans le système socio-fiscal français, les droits sociaux ou les avantages fiscaux sont rarement octroyés de manière automatique aux individus qui remplissent les conditions d'attribution. Lorsqu'ils ne doivent pas faire l'objet d'une demande spécifique, ils reposent *a minima* sur la déclaration d'un changement de situation économique ou familiale. Rien ne va pourtant de soi dans ces déclarations aux administrations puisqu'on estime à un tiers la part des foyers éligibles au RSA qui n'en ferait pas la demande [@hannafi2022]. Si la méconnaissance des règles fiscales explique une partie du non-recours à certains avantages [@spire2012], c'est loin d'être la seule explication pour les prestations sociales [@warin2014]. Les classes populaires, et en particulier les femmes y appartenant, sont plus que les autres, socialisées à la gestion du travail administratif qu'implique la perception de prestations sociales [@siblot2006] et qui fait partie intégrante du "travail de subsistance" [@laville2019]. C'est d'avantage le stigmate qui porte sur les "assistés" qui "profitent" du système, souvent intériorisé par les individus éligibles eux-mêmes [@paugam2009] qui peut expliquer que certains individus, refusant de "demander l'aumône" [@siblot2006], ne fasse pas les démarches nécessaires pour obtenir les prestations auxquelles ils ont *a priori* droit.

De la même manière que faire une demande de prestation suppose de savoir que l'on est éligible et de considérer que l'on est légitime à percevoir cette prestation, on peut penser que déclarer un changement de situation à la CAF ou au fisc met en jeu la connaissance des effets de cette déclaration sur les droits sociaux et avantages fiscaux et la perception de la légitimité de ceux-ci : *à quelles conditions un transfert entre personnes apparentées ou une nouvelle relation conjugale est considéré comme devant faire l'objet d'une déclaration au fisc ou la CAF ?* C'est justement la production de ces réponses à l'intérieur des familles que l'on voudrait étudier en tant qu'arrangements. Ces déclaration mettent aussi en jeu des choix permis par le droit d'option : *Comment choisit-on l'allocataire principal à la CAF ou le parent déclarant les parts fiscales que représentent les enfants* ? L'État social semble, en permanence, demander aux couples de produire des consensus formalisables selon les termes des administrations. Etudier les arrangements ainsi produits suppose d'interroger le travail de traduction effectué par les individus pour traduire l'état de leurs relations dans le langage des institutions de l'État social, pour qu'il coïncide avec les catégories administratives. Cela suppose de questionner les modalités de production de ce consensus sur les relations et son caractère éventuellement conflictuel. L'État social effectue aussi un travail de normalisation des situations individuelles qui s'opère par un travail "d'inculcation des catégories d'État" [@dubois2015, p.15]. *Deux personnes ayants des rapports sexuels et partageant un appartement se considèrent-elles en couple car la CAF le fait ? Un beau-père ou une belle-mère considère il les enfants de son conjoint comme les siens si ceux-ci sont à sa charge fiscale ?* Il s'agira donc de prêter attention à la manière dont les catégories familiales des administrations informent, en retour, les catégories ordinaires de description des relations familiales et conjugales. Enfin, il sera particulièrement intéressant d'étudier les pratiques de mise en conformité des relations avec des catégories administratives, par exemple, par recours au mariage au pacs pour être considéré comme couple aux yeux du fisc. Il s'agit là d'autant de pratiques qui peuvent être sous-tendu par une logique économique. Ces pratiques, nécessairement tributaires de la capacité à "domestiquer" [@spire2011], les règles fiscales et sociales, ne peuvent être analyser que comme des pratiques situées socialement. Enfin ces pratiques ne produisent pas nécessairement des effets identiques sur tous les individus du foyer ou ménage concerné. PLus généralement, étudier ces arrangements familiaux lié aux enjeux de déclaration aux administrations sociales ou fiscales permettra d'analyser modalités selon lesquelles les catégories administratives façonnent les relations familiales.

## [Axe 3.]{.underline} Partage de la charge fiscale et appropriation des prestations familiales : étudier le marquage de genre des revenus de transferts

La faiblesse de l'encadrement par l'État de la répartition des revenus, de la participation aux dépenses ou de la mise en commun des ressources dans un couple autorise largement les arrangements sur le partage de l'argent provenant des prestations sociales ou sur le paiement des impôts directs.

modalité par défaut : PAS ou allocataire principale

## [Axe 4]{.underline}. Les effets distributifs des arrangements socio-fiscaux sur la répartition secondaire des revenus :

S'il est sans doute vrai que ces pratiques sont moins diversifiées et que les montants concernés sont sans commune mesure la fraude ou l'optimisation fiscale pratiquée par les ultra-riches, l'intérêt d'étudier ces pratiques ne réside pas ici. En effet, le système socio-fiscal par la progressivité de l'impôt sur le revenu ou les conditions de ressources sur lesquelles sont basées l'attribution de prestations sociales ont, *a priori*, un effet redistributif entre ménages. Le caractère effectif de la redistributivité de l'ensemble du système socio-fiscal entre ménages de différents niveau de vie a été discuté, en particulier pour les 5% les plus riches [@piketty2013], s'expliquant largement par des pratiques de fraudes mais surtout d'optimisation des classes dominantes [@spire2012]. De même la familialisation de l'impôt a fait l'objet de critiques car celle-ci organise une redistribution envers les couples mariés et pacsés les plus aisés [@andré2019], allant jusqu'à proposer d'individualiser l'impôt sur les revenus [@piketty2003]. Moins nombreux sont les travaux portants sur les effets redistributifs du système socio-fiscal entre homme et femmes. Du fait de leur sur-représentation parmi les ménages modestes et les parents de familles monoparentales, les femmes semblent bénéficier un peu plus que les hommes du système de redistribution : celui-ci réduit de 35% le taux de pauvreté des femmes, contre 34% pour les hommes et de 50% l'intensité de la pauvreté des femmes, contre 48% pour les hommes [@cabannes2023]. Pourtant, les effets du système socio-fiscal sur la répartition secondaires des revenus entre groupes sociaux de sexe sont difficilement appréciables si l'on reste à l'échelle du ménage : le mode calcul du niveau vie à l'échelle du ménage, véritable "cache-sexe" des inégalités de genre [@bessière2016], uniformise nécéssairement le niveau de vie des hommes et femmes en couple. Pourtant, selon les choix opérés dans un couple en matière de formalisation administrative des relations, de cohabitation, de déclaration des revenus et de partage de la charge fiscale, l'impôt sur le revenu peut avoir des effets anti-redistributifs entre conjoint·e·s [@carbonnier2016]. En étudiant ces arrangements familiaux, à la fois dans le ménage, entre conjoints cohabitants, mais aussi au delà de celui-ci, entre ex-conjoints ne cohabitant plus, il sera ineteressant que questionner leur effets potentiels sur la redistributivité du système socio-fiscal, entre groupes sociaux de sexe et de classe. L'effet produit par l'ensemble des dispositifs de prestations sociales et d'avantages fiscaux sur les inégalités économiques informe en effet les perception qu'on les individus de ceux-ci, et partant le rapport à l'État qu'ils entretiennent [@spire2018]. Il s'agira donc d'interroger ces effets au prisme du rapport à l'Etat, et en particulier l'État social, qu'entretiennent les individus, selon leur classe et groupe social de sexe d'appartenance.

# Dispositif méthodologique envisagé

## Volet qualitatif

Le volet qualitatif de ce travail de doctorat s'appuiera sur la réalisation de monographies familiales, selon la méthode proposée par Florence Weber [-@gojard2003]. Le recrutement des enquêtés sera réalisée par la participation à une post-enquête Emploi du Temps de l'INSEE

mais en amont des administrations, avant que celle-ci ne puisse les saisir. Pertinence théorique pour voir ce que les catégories d'administration des populations font au catégories familiales ordinaires, mais difficulté méthodologique, parce qu'on ne s'interesse pas à quelque chose qu'on peut circonscrire de mannière instuuinelle, mais à ce qui se passe dans l'itimité familiale. donc terrain blablabl.

## Volet quantitatif

Le volet quantitatif de ce travail de recherche s'appuiera essentiellement sur l'exploitation de l'enquête sur les revenus fiscaux et sociaux (ERSF) disponible sur le réseau Quetelet. Produit de l'appariement entre l'enquête emploi en continu, les fichiers de déclaration des revenus fiscaux ainsi que les fichiers des prestations sociales versées par la CNAF, la CNAV et la MSA, elle contient des données à l'échelle du ménages comme des individus qui le compose. Cette enquête sera utilisée pour réaliser des statistiques descriptives sur le montant des prestations sociales perçues et des impôts payés. On exploitera également cette enquête avec le modèle INES, modèle de micro-simulation statique du système socio-fiscal français développé par l'INSEE et la DREES [@fredon2020] et dont le code source R devrait être publié au printemps prochain[^1]. Il sera alors possible d'introduire des hypothèses portant sur la répartition des ressources et des dépenses liées aux presttaions sociales et aux impôts directs dans les familles, ce qui permettra de réaliser des simulations des effets distributifs du système socio-fiscal entre groupes sociaux de sexe.

[^1]: Dans l'hypothèse où ce calendrier serait retardé, le responsable actuel d'INES a confirmé pouvoir me transmettre la dernière version du code.

## Calendrier prévisionnel

# Bibliographie {.page-break-before}

::: {#refs}
:::

# TRASH {.page-break-before}

[Que l'on considère les polémique autour autour de l'usage des allocations de rentrée scolaire, au marronnier des pauvres qui feraient des enfants pour allocations ou plus réclament à l'indignation suscité par un youtubeur, Mertel B, se vantant de toucher près de 1 800 euros d'aides sociales sans occuper d'emploi, c'est d'avantage le droit de recourir librement à ses droits et de disposer des revenus ainsi perçus que la fraude - en générale inexistante - qui est condamné.]

, à tel point qu'elles remettent en cause la redistributivité de l'impôt en France [@piketty2013].

S'il est vrai que les montants concernés par ces pratiques sont sans commune mesure avec ceux concernés par la fraude fiscale et que les classes populaires font l'objet d'un encadrement resserré par les administrations sociales, il reste un domaine dans lequel le système socio-fiscal laisse, dans toutes les strates sociales, de marges de manœuvres : celui de la famille[^2]. En effet,

[^2]: C'est d'ailleurs un des leviers de la « domestication » de l'impot par les classes dominantes étudié par Alexis Spire

En 2019, la réforme du prélèvement à la source de l'impôt sur le revenu (IR) instaure un partage par défaut de la charge fiscale entre conjoint·e·s marié·e·s ou pacé·e·s. Un taux dit *personnalisé* est calculé pour chaque foyer fiscal et appliqué de manière identique aux salaires des deux conjoint·e·s. Il reste possible, pour les conjoint·e·s, de fixer librement un taux dit *individualisé*, c'est à dire propre à chacun·e. Ainsi, cette réforme établit le partage proportionnel de la charge fiscale comme norme dans les couples, et fait apparaître tout autre arrangement comme marginal. Cette logique proportionnelle s'oppose, *a priori*, à la logique de l'imposition des revenus en France, qui depuis 1916 est se fait via un impôt progressif.

blablabla l'Etat et les rapports sociaux de sexe.

[Grande question : système socio-fiscal et rapport sociaux]{.underline}

Pourtant, devant les mobilisation en faveur de la déconjugalisation de certaines prestation sociale, comme l'Allocation Adulte Handicapé

Ceci s'explique pour partie par la domination du ménage comme unité statistique de référence dans les grandes enquêtes économiques de la statistique publique, qui rend difficile l'accèes à des données à l'échelle de l'individu, et a pour effet de creer une fiction d'égalité entre conjoint.e.s.

Or si le système socio-fiscal encadre très fortement les individus appartenant aux classes sociales modestes, qui sont à la fois exlcus des processus de décisons déterminant la mise en place des règles socio-fiscales, **(Spire domestication de l'impôt)**, objets de contrôles privilégiés **(Dubois, ??)** et plus fortement condamnés pour leurs illéglismes **(Spire, gestion des illegalismes)**, dans l'ensemble de la société, l'encadrement des choix qui peuvent être opérés au sein des couples reste relativement faible.

qui ne sont pas a envisager comme des incohérences entre les différentes

et que les arrangements avec celui-ci sont socialement plus fortement condamnés

Or, le système sociofiscal laisse une place importante aux arrangements conjugaux en matière de déclaration

# Grandes questions :

-   Etat et ordre du genre, de classe, de race, d'âge
-   Effets distributifs du système socio-fiscal au sein des couples !

# conseils projet de thèse

-   grande idée grande question, à la fois théorique et d'actualité

-   grands enjeux, politiques, théoriques, d'actualité

-   procéder par analyse, une question, et on décompose.

-   problématique, objet pour traiter cette problématique, méthode.

individualisation de l'AAH?

rapidement positionnement dans les quelques références bibliographiques centrales

-   Spire sur l'appropriation des règles fiscales par les classes dominantes +

-   Dubois sur les contrôles caf

-   Bessière sur les arrangements

-   Bessière et Gollac sur le genre des arrangements avec la fiscalité de l'héritage

donc comment est ce que les catégories administratives façonnent aussi les relations familiales.

A l'inverse, les classes dominantes ont opéré une "domestication de l'impôt" qui leur permet tirer profit des règles de celui-ci [@spire2011].

[@dubois2021 ; @cartier2008]

-\> des droits certes, mais pas automatiques, donc il faut demander, se sentir légitime a demander une aide, idée qu'on se fait de la légitimité à percevoir certaines allocations

-\> droit d'option, meme quand on choisit de déclarer une situation pour demander une aide ou que cela va nous en faire perdre une, alors, parfois on a le choix

-\> donc comment est ce qu'on fait rentrer la réalité de la situation dans des catgéories administatives. du coup comment est ce que sont produit ces consensus au sein des familles ? quels confits ? le plus souvent on peut se dire qu'il ne se passe pas grand chose, mais en réalité sur certains droits sociaux.

-\> inversement comment est ce que ces catgéories administatives informent les catgéories familiales et conjugales ordinaires : est ce qu'on se considère en couple si on est pas en couple aux yeux de la CAF ?

-\> possibilité aussi de modifier la réalité pour la faire renter dans des catgéories administrauves : se marier pour les impots, etre en couple pour avoir plus d'APL... ou inversement attendre avant de cohabiter aprce qu'on perd des aides sociales si c'est le cas

-\> donc comment est ce que les catgéories administatives faconnent aussi les relations familiales.

-\> comment est ce que

Pour autant, rien ne va de soit dans une telle déclaration. (cf non recours par exemple)

On peut donc se demander comment est produit un consensus sur ce que sont l'état des relation familiales et donc sur la manière dont celle-ci doit être ou non déclarée comme telle aux institutions sucéptibles

Technicité mais aussi sens commun fiscal

distance ou proximité // droit

comment les individus font renter leur situtation dans les catégories administatives ?

faire sociologie de la déclaration

classes populaire et Etat :

Les fractions « intégrées » des classes populaires appartiennent au premier quand les « pauvres » -- 8 millions de personnes, soit 13,5 % de la population en 2012 -- dépendent désormais du second [D[uvoux]{.smallcaps}, 2012].

 Lors d'une enquête dans un quartier pavillonnaire, nombre d'habitants originaires des classes populaires en petite ascension tenaient des propos accusateurs envers ceux qui « profitent » des aides sociales quand eux-mêmes mettaient en avant leur courage au travail et leur « mérite » [C[artier]{.smallcaps} *et al.*, 2008].

Cette représentation des personnes situées en bas de l'échelle sociale comme « profitant » du système est pourtant en décalage avec le fait que beaucoup ne recourent pas à leurs droits. Près des deux tiers des allocataires potentiels du complément d'activité destiné aux travailleurs modestes (le « RSA activité ») ne le demandent pas [D[uvoux]{.smallcaps}, 2012, p. 12].

Dans *La vie au guichet*, ouvrage sur les relations entre agents d'une Caisse d'allocations familiales et usagers, Vincent Dubois [2012a] témoigne explicitement de cette double ambition. Cet ouvrage insiste sur la domination qui s'exerce à l'encontre des classes populaires dans les interactions au guichet. C'est à travers elles que « s'opère en pratique l'inculcation des catégories d'État », qui, en outre, imposent parfois aux individus des statuts différents de la manière dont eux-mêmes se perçoivent (avec des phrases du type « Vous ne voulez pas l'admettre mais vous formez bien un couple », « Non, vous n'êtes pas considérée comme mère de famille ») [p. 18-19]. À la complexité administrative qui laisse les populations dépourvues du capital culturel suffisant désemparées, s'ajoutent des injonctions qui peuvent être des condamnations morales (« Il faudrait peut-être arrêter de changer de partenaire ! », « Et du travail, vous en cherchez vraiment ? »). Cependant, les allocataires ne subissent pas passivement ces impositions : *La vie au guichet* donne à voir des individus qui, même particulièrement démunis, échappent pour partie à la domination à travers le retrait, la contestation, la dérision et certaines formes de réappropriation de la relation avec les agents de la CAF.

Se centrant sur les bénéficiaires du RMI, Nicolas Duvoux distingue pour sa part trois types d'allocataires en fonction de leur rapport à cette prestation sociale et à l'ensemble des significations qui en découlent : l'autonomie intériorisée, l'autonomie contrariée, le refus de la dépendance. Dans le premier cas (autonomie intériorisée), les allocataires adhèrent à la norme d'autonomie véhiculée par les travailleurs sociaux et considèrent le RMI comme transitoire. Dans le second cas (autonomie contrariée), les allocataires expriment leur difficulté à se conformer aux exigences en matière d'autonomie. Ils sont durablement installés dans l'assistance et ont établi une relation de confiance avec les personnes chargées de leur suivi. Leur discours, quant aux institutions en général, est cependant plus ambivalent : elles sont perçues tout à la fois comme consolantes et excluantes. Dans le troisième cas (refus de la dépendance), la norme d'autonomie est contestée et les contacts avec les agents institutionnels sont très ambivalents, marqués par des tentatives de retournement du stigmate [D[uvoux]{.smallcaps}, 2009]. Si l'on peut supposer que ces typologies [voir aussi P[augam]{.smallcaps}, 2005, 2009] renvoient pour partie à des strates différentes des classes populaires, l'équivalence n'est toutefois pas totale dans la mesure où la catégorie d'assistés qui les sous-tend regroupe des individus aux profils sociaux hétérogènes (une partie des assistés proviennent des classes moyennes voire supérieures).
